// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';

// main
export const SET_RUNNING_TEXT = 'SET_RUNNING_TEXT';

//
export const ADD_REQUEST_LIST = 'ADD_REQUEST_COUNT';
export const MIN_REQUEST_LIST = 'MIN_REQUEST_COUNT';
export const SET_REQUEST_LIST = 'SET_REQUEST_LIST';
export const ADD_REQUEST_COUNT = 'ADD_REQUEST_COUNT';
export const MIN_REQUEST_COUNT = 'MIN_REQUEST_COUNT';
export const SET_REQUEST_COUNT = 'SET_REQUEST_COUNT';
export const ADD_REQUEST_PERBANKAN_COUNT = 'ADD_REQUEST_PERBANKAN_COUNT';
export const MIN_REQUEST_PERBANKAN_COUNT = 'MIN_REQUEST_PERBANKAN_COUNT';
export const SET_REQUEST_PERBANKAN_COUNT = 'SET_REQUEST_PERBANKAN_COUNT';
export const ADD_REQUEST_PPAT_COUNT = 'ADD_REQUEST_PPAT_COUNT';
export const MIN_REQUEST_PPAT_COUNT = 'MIN_REQUEST_PPAT_COUNT';
export const SET_REQUEST_PPAT_COUNT = 'SET_REQUEST_PPAT_COUNT';
export const ADD_REQUEST_NOTARIS_COUNT = 'ADD_REQUEST_NOTARIS_COUNT';
export const MIN_REQUEST_NOTARIS_COUNT = 'MIN_REQUEST_NOTARIS_COUNT';
export const SET_REQUEST_NOTARIS_COUNT = 'SET_REQUEST_NOTARIS_COUNT';
export const ADD_JOB_COUNT = 'ADD_JOB_COUNT';
export const SET_JOB_COUNT = 'SET_JOB_COUNT';
